spring:
  datasource:
    url: jdbc:mysql://localhost:3306/succulentShop
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: thekomshija@gmail.com
    password: bdxo chrt gdpz jprr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      globally_quoted_identifiers: true
file:
  upload-dir: ${user.home}/succulent-shop/uploads

  logging:
    level:
      org.springframework.web: INFO
      com.m4rkovic.succulent_shop: DEBUG  # Add this to see more detailed logs for your application
      org.hibernate.SQL: DEBUG  # Add this if you want to see SQL queries

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    com.m4rkovic.succulent_shop.controller: DEBUG
#    com.m4rkovic.succulent_shop.service: DEBUG
#    root: INFO
#    com.m4rkovic.succulent_shop: DEBUG
#    org.springframework: INFO
#    org.hibernate: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/application.log
#    max-size: 10MB
#    max-history: 30